# Generated by Django 2.1.15 on 2020-07-12 17:50

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recipie'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.recipe_image_file_path),
        ),
    ]
